#' Create UpSet plot for set intersections
#'
#' Creates an UpSet-style plot showing set intersections between groups.
#' The plot consists of two panels: a bar plot showing intersection sizes
#' and a matrix plot showing which sets are included in each intersection.
#'
#' @param df A data frame with at least two columns: one for items
#'   and one for sets/groups
#' @param item_col Character. Name of the column containing items. Default: `"item"`
#' @param set_col Character. Name of the column containing sets/groups. Default: `"set"`
#' @param set_colors Named vector of colors for each set. If NULL (default), uses default
#'   ggplot2 colors generated by `scales::hue_pal()`.
#' @param degree_colors Vector of colors for different intersection degrees (sizes).
#'   If NULL (default), uses default ggplot2 discrete fill scale, which automatically
#'   adapts to any number of intersection degrees.
#' @param base_theme ggplot2 theme object for the bar plot. Default: `get_default_theme()`
#' @param log10_scale Logical. If TRUE, uses log10 scale for the Y-axis in the bar plot.
#'   Default: FALSE
#' @param return_list Logical. If TRUE, returns a list of two ggplot objects (matrix and bar).
#'   If FALSE, returns a combined plot using patchwork. Default: FALSE
#'
#' @return Either a combined patchwork plot (if `return_list = FALSE`) or a list
#'   containing two ggplot objects: the matrix plot and the bar plot
#'
#' @examples
#' \dontrun{
#' # Create example data
#' df <- data.frame(
#'   item = c("A", "B", "C", "D", "E", "F"),
#'   set = c("X", "X", "Y", "Y", "Z", "Z")
#' )
#' plot_upset(df)
#'
#' # With custom set colors
#' plot_upset(df, set_colors = c(X = "red", Y = "blue", Z = "green"))
#'
#' # With custom degree colors (for intersection sizes)
#' plot_upset(df, degree_colors = c("lightblue", "steelblue", "darkblue"))
#'
#' # With log10 scale for Y-axis
#' plot_upset(df, log10_scale = TRUE)
#'
#' # Return individual plots
#' plots <- plot_upset(df, return_list = TRUE)
#' }
#'
#' @export
plot_upset <- function(df,
                       item_col = "item",
                       set_col = "set",
                       set_colors = NULL,
                       degree_colors = NULL,
                       base_theme = get_default_theme(),
                       log10_scale = FALSE,
                       return_list = FALSE) {
  # Prepare the matrix data
  matrix_data <- prepare_upset_matrix(df, item_col, set_col)

  # Generate default colors if not provided
  if (is.null(set_colors)) {
    sets <- unique(df[[set_col]])
    set_colors <- scales::hue_pal()(length(sets))
    names(set_colors) <- sets
  }

  p.mat <- plot_upset_matrix(matrix_data, set_colors, base_theme)
  p.bar <- plot_upset_bar(matrix_data, degree_colors, base_theme, log10_scale)

  if (return_list) {
    return(list(bar = p.bar, matrix = p.mat))
  } else {
    p <- p.bar + p.mat + patchwork::plot_layout(ncol = 1)
    return(p)
  }
}

#' Prepare matrix data for upset plot
#'
#' Internal function to prepare the data structure needed for upset plotting
#'
#' @param df Input data frame
#' @param item_col Name of the item column
#' @param set_col Name of the set column
#'
#' @return A list with `matrix` and `segment` data frames
#' @keywords internal
prepare_upset_matrix <- function(df, item_col, set_col) {
  # Rename columns for consistent processing
  df_renamed <- df
  names(df_renamed)[names(df_renamed) == item_col] <- "item"
  names(df_renamed)[names(df_renamed) == set_col] <- "set"

  matrix <-
    dplyr::group_by(df_renamed, item) %>%
    dplyr::summarize(sets = list(set), .groups = "drop") %>%
    dplyr::ungroup() %>%
    dplyr::mutate(sets_collapsed = factor(purrr::map_chr(sets, function(x) {
      paste0(sort(x), collapse = "-")
    }))) %>%
    dplyr::group_by(sets, sets_collapsed) %>%
    dplyr::summarize(count = dplyr::n(), degree = length(sets[[1]]), .groups = "drop") %>%
    dplyr::ungroup() %>%
    dplyr::mutate(sets_collapsed = factor(
      sets_collapsed,
      levels = sets_collapsed[order(degree, count, decreasing = TRUE)]
    )) %>%
    tidyr::unnest(sets) %>%
    dplyr::mutate(sets = forcats::fct_rev(sets))

  segment <-
    dplyr::mutate(matrix, sets = factor(sets, ordered = TRUE)) %>%
    dplyr::group_by(sets_collapsed) %>%
    dplyr::summarize(y = min(sets), yend = max(sets), .groups = "drop")

  list(matrix = matrix, segment = segment)
}

#' Plot UpSet matrix panel
#'
#' Creates the matrix visualization showing which sets are included in each intersection
#'
#' @param matrix_data List containing `matrix` and `segment` data frames from
#'   `prepare_upset_matrix()`
#' @param set_colors Named vector of colors for each set
#' @param base_theme ggplot2 theme used to derive label text size
#'   (default: `get_default_theme()`)
#'
#' @return A ggplot2 object
#' @export
plot_upset_matrix <- function(matrix_data, set_colors,
                              base_theme = get_default_theme()) {
  matrix <- matrix_data$matrix
  segment <- matrix_data$segment

  label_size <- base_theme$text$size * 0.8

  # Determine number of sets for alternating background
  n_sets <- length(unique(matrix$sets))

  ggplot() +
    geom_rect(
      aes(
        xmin = xmin,
        xmax = xmax,
        ymin = ymin,
        ymax = ymax
      ),
      data = tibble::tibble(
        xmin = 0.5,
        xmax = Inf,
        ymin = -0.5 + seq(n_sets),
        ymax = 0.5 + seq(n_sets)
      ),
      fill = rep_len(c("#F2F2F2", "white"), n_sets)
    ) +
    scale_y_discrete() +
    scale_x_discrete() +
    geom_segment(
      aes(
        x = sets_collapsed,
        xend = sets_collapsed,
        y = y,
        yend = yend
      ),
      data = segment
    ) +
    geom_point(
      aes(sets_collapsed, sets, color = sets),
      data = matrix
    ) +
    theme_void() +
    theme(
      axis.text.y = element_text(size = label_size),
      legend.position = "none",
      plot.margin = margin(0, 0.1, 0.1, 0.1, unit = "cm")
    ) +
    scale_color_manual(values = set_colors)
}

#' Plot UpSet bar panel
#'
#' Creates the bar chart showing the size of each set intersection
#'
#' @param matrix_data List containing `matrix` data frame from `prepare_upset_matrix()`
#' @param degree_colors Vector of colors for different intersection degrees. If NULL (default),
#'   uses ggplot2's default discrete fill scale.
#' @param base_theme ggplot2 theme object
#' @param log10_scale Logical. If TRUE, uses log10 scale for the Y-axis. Default: FALSE
#'
#' @return A ggplot2 object
#' @export
plot_upset_bar <- function(matrix_data, degree_colors = NULL, base_theme, log10_scale = FALSE) {
  matrix <- matrix_data$matrix

  p <- dplyr::distinct(matrix, sets_collapsed, count, degree) %>%
    ggplot(aes(sets_collapsed, count)) +
    geom_text(aes(label = scales::comma(count)), vjust = -0.5, size = 2) +
    geom_col(aes(fill = factor(degree))) +
    base_theme +
    theme(
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      legend.position = "none"
    ) +
    labs(y = "No. items") +
    coord_cartesian(clip = "off")

  # Add color scale - use manual if provided, otherwise ggplot2 defaults
  if (!is.null(degree_colors)) {
    p <- p + scale_fill_manual(values = degree_colors)
  }

  # Add appropriate Y-axis scale
  if (log10_scale) {
    p <- p + scale_y_log10(labels = scales::label_comma(), expand = expansion(c(0, 0.05), 0))
  } else {
    p <- p + scale_y_continuous(labels = scales::label_comma(), expand = expansion(c(0, 0.05), 0))
  }

  p
}
